[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
serde = "1.0.119"
reqwasm = "0.5.0"
wasm-bindgen-futures = "0.4.30"
wasm-bindgen = "0.2.80"
